version: "3.7"
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    hostname: nifi
    ports:
      - '8080:8080' # Unsecured HTTP Web Port
      - '8443:8443'
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - TZ="UTC"
      - AUTH=tls
      - KEYSTORE_PATH=/opt/certs/server_keystore.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=SuperSecret
      - TRUSTSTORE_PATH=/opt/certs/server_truststore.jks
      - TRUSTSTORE_PASSWORD=SuperSecret
      - TRUSTSTORE_TYPE=JKS
      - INITIAL_ADMIN_IDENTITY=CN=Random User

    networks:
      - dbt_sample_network
    volumes:
      - ./nifi-ssl:/opt/certs
networks:
  dbt_sample_network:
    driver: bridge
